pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build') {
            steps {
                dir('hello-app') {
                    sh 'pwd'
                    sh 'ls -la'
                    sh 'mvn clean package'
                }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('hello-app') {
                    withSonarQubeEnv('SonarQube') {
                        sh '''
                            mvn clean verify sonar:sonar \
                            -Dsonar.ws.timeout=300
                        '''
                    }
                }
            }
        }

    }

    post {
        success {
            echo 'Build and SonarQube Analysis completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Please check the Jenkins Console Output.'
        }
        always {
            cleanWs()
        }
    }
}